<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Dao;

use App\Domain\Dao\Generated\BaseResetPasswordTokenDao;
use App\Domain\Model\ResetPasswordToken;
use TheCodingMachine\GraphQLite\Annotations\Factory;
use TheCodingMachine\GraphQLite\Annotations\HideParameter;

/**
 * The ResetPasswordTokenDao class will maintain the persistence of ResetPasswordToken class into the reset_password_tokens table.
 */
class ResetPasswordTokenDao extends BaseResetPasswordTokenDao
{
    /**
     * @Factory
     * @HideParameter(for="$lazyLoading")
     */
    public function getById(string $id, bool $lazyLoading = false): ResetPasswordToken
    {
        return parent::getById($id, $lazyLoading);
    }
}
