.MR rules:
  rules:
    - # Target only merge request
      if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
.rc rules:
  rules:
    - # Target only tags "a.b.c-rcX" and main branch
      if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-rc\.\d+$/ || $CI_COMMIT_REF_NAME =~ /^main/'
.stable rules:
  rules:
    - # Target only tags "a.b.c"
      if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
.hotfix rules:
  rules:
    - # Target tags and branches named `hotfix/...`
      if: '$CI_COMMIT_TAG =~ /^hotfix\// || $CI_COMMIT_REF_NAME =~ /^hotfix\//'
.except hotfix rules:
  rules:
    - # Target tags and branches named `hotfix/...`
      if: '$CI_COMMIT_TAG =~ /^hotfix\// || $CI_COMMIT_REF_NAME =~ /^hotfix\//'
      when: never


workflow:
  rules:
    - # avoid duplicates pipeline
      if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - !reference [.MR rules, rules]
    - !reference [.rc rules, rules]
    - !reference [.stable rules, rules]
    - !reference [.hotfix rules, rules]
    - !reference [.except hotfix rules, rules]
